import { pgTable, text, integer, boolean, timestamp, jsonb, doublePrecision, serial } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(),
  email: text('email'),
  phone: text('phone'),
  passwordHash: text('password_hash'),
  fullName: text('full_name'),
  role: text('role').default('CUSTOMER'),
  dateOfBirth: text('date_of_birth'),
  gender: text('gender'),
  isActive: boolean('is_active').default(true),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const admins = pgTable('admins', {
  id: text('id').primaryKey(),
  username: text('username').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  fullName: text('full_name').notNull(),
  role: text('role').notNull().default('STORE_MANAGER'),
  phone: text('phone'),
  email: text('email'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').defaultNow(),
  lastLoginAt: timestamp('last_login_at'),
});

export const categories = pgTable('categories', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  image: text('image'),
});

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  categoryId: text('category_id'),
  category: text('category'),
  subCategory: text('sub_category'),
  description: text('description'),
  price: integer('price').notNull(),
  mrp: integer('mrp').notNull(),
  discount: integer('discount').default(0),
  sizes: jsonb('sizes'),
  colors: jsonb('colors'),
  stock: integer('stock').notNull().default(0),
  sku: text('sku'),
  status: text('status').default('PUBLISHED'),
  isFeatured: boolean('is_featured').default(false),
  isNewArrival: boolean('is_new_arrival').default(false),
  isBestseller: boolean('is_bestseller').default(false),
  isActive: boolean('is_active').default(true),
  images: jsonb('images'),
  rating: doublePrecision('rating').default(4.8),
  reviewsCount: integer('reviews_count').default(0),
  material: text('material'),
  careInstructions: text('care_instructions'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const coupons = pgTable('coupons', {
  id: text('id').primaryKey(),
  code: text('code').notNull().unique(),
  discountType: text('discount_type').notNull(),
  discountValue: integer('discount_value').notNull(),
  minOrderAmount: integer('min_order_amount').default(0),
  maxDiscountAmount: integer('max_discount_amount'),
  usageLimit: integer('usage_limit').default(500),
  usageCount: integer('usage_count').default(0),
  isActive: boolean('is_active').default(true),
  expiresAt: timestamp('expires_at'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const customerAddresses = pgTable('customer_addresses', {
  id: text('id').primaryKey(),
  userId: integer('user_id').references(() => users.id, { onDelete: 'cascade' }),
  fullName: text('full_name').notNull(),
  mobileNumber: text('mobile_number').notNull(),
  houseBuilding: text('house_building').notNull(),
  streetArea: text('street_area').notNull(),
  villageTownCity: text('village_town_city').notNull(),
  postOffice: text('post_office'),
  district: text('district').notNull(),
  state: text('state').notNull(),
  pinCode: text('pin_code').notNull(),
  landmark: text('landmark'),
  addressType: text('address_type').notNull().default('HOME'),
  isDefault: boolean('is_default').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const postalCodes = pgTable('postal_codes', {
  id: text('id').primaryKey(),
  pincode: text('pincode').notNull(),
  postOffice: text('post_office').notNull(),
  district: text('district').notNull(),
  state: text('state').notNull(),
  city: text('city'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const orders = pgTable('orders', {
  id: text('id').primaryKey(),
  userId: text('user_id'),
  orderStatus: text('order_status').notNull().default('NEW'),
  status: text('status').notNull().default('NEW'),
  paymentMethod: text('payment_method').notNull(),
  paymentStatus: text('payment_status').notNull().default('PENDING'),
  customer: jsonb('customer').notNull(),
  shippingAddress: jsonb('shipping_address').notNull(),
  shippingName: text('shipping_name'),
  shippingPhone: text('shipping_phone'),
  shippingAddressLine: text('shipping_address_line'),
  shippingCity: text('shipping_city'),
  shippingDistrict: text('shipping_district'),
  shippingState: text('shipping_state'),
  shippingPincode: text('shipping_pincode'),
  trackingToken: text('tracking_token'),
  currentLocation: text('current_location'),
  expectedDeliveryDate: text('expected_delivery_date'),
  items: jsonb('items').notNull(),
  pricing: jsonb('pricing').notNull(),
  totalAmount: integer('total_amount').notNull(),
  taxBreakdown: jsonb('tax_breakdown'),
  razorpayOrderId: text('razorpay_order_id'),
  razorpayPaymentId: text('razorpay_payment_id'),
  courierName: text('courier_name').default('Delhivery Express'),
  trackingNumber: text('tracking_number'),
  awbNumber: text('awb_number'),
  invoiceNumber: text('invoice_number'),
  estimatedDelivery: text('estimated_delivery').default('3 - 5 Business Days'),
  timeline: jsonb('timeline'),
  customerNote: text('customer_note'),
  adminNote: text('admin_note'),
  paymentDetails: jsonb('payment_details'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const orderTrackingEvents = pgTable('order_tracking_events', {
  id: text('id').primaryKey(),
  orderId: text('order_id').references(() => orders.id, { onDelete: 'cascade' }),
  trackingNumber: text('tracking_number').notNull(),
  status: text('status').notNull(),
  locationName: text('location_name'),
  location: text('location'),
  city: text('city'),
  district: text('district'),
  state: text('state'),
  pincode: text('pincode'),
  latitude: doublePrecision('latitude'),
  longitude: doublePrecision('longitude'),
  description: text('description').notNull(),
  source: text('source').notNull().default('SYSTEM'),
  scannedBy: text('scanned_by'),
  scannedAt: timestamp('scanned_at').defaultNow(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const parcelScanEvents = pgTable('parcel_scan_events', {
  id: text('id').primaryKey(),
  orderId: text('order_id').references(() => orders.id, { onDelete: 'cascade' }),
  trackingNumber: text('tracking_number').notNull(),
  scanType: text('scan_type').notNull(),
  locationName: text('location_name').notNull(),
  city: text('city'),
  district: text('district'),
  state: text('state'),
  pincode: text('pincode'),
  latitude: doublePrecision('latitude'),
  longitude: doublePrecision('longitude'),
  scannedBy: text('scanned_by').notNull(),
  scannedAt: timestamp('scanned_at').defaultNow(),
});

export const qrScanEvents = pgTable('qr_scan_events', {
  id: text('id').primaryKey(),
  orderId: text('order_id').references(() => orders.id, { onDelete: 'cascade' }),
  trackingNumber: text('tracking_number').notNull(),
  scannedBy: text('scanned_by'),
  scannerType: text('scanner_type').notNull(),
  location: text('location'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const banners = pgTable('banners', {
  id: text('id').primaryKey(),
  title: text('title').notNull(),
  subtitle: text('subtitle'),
  ctaText: text('cta_text'),
  link: text('link'),
  badge: text('badge'),
  image: text('image').notNull(),
  isActive: boolean('is_active').default(true),
  sortOrder: integer('sort_order').default(0),
});

export const storeSettings = pgTable('store_settings', {
  id: text('id').primaryKey().default('default'),
  settings: jsonb('settings').notNull(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
